name: codecov

on: [push]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.8
      uses: actions/setup-python@master
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

    - name: Generate coverage report
      run: |
        pip install pytest pytest-cov
        pytest --cov=nujo --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
